# Possible future move over to GitHub actions.
# Taken from another project, not ready for yahoo-finance2 yet.
# But, both gist_ids below are newly created for yahoo-finance2.
#
# TODO (at least)
# - Need to make sure we cover everything from .circle/ci.config
# - Any caching we can do.
name: Tests
on:
  push:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_call:
  workflow_dispatch:
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    permissions:
      id-token: write # for codecov

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - run: deno fmt --check
      - run: deno lint

      - name: Run tests, produce coverage
        run: deno task test --coverage

      - name: Codecov
        uses: codecov/codecov-action@v5
        with:
          use_oidc: true

      #      - name: Prepare packages for next step (remove after non-sha release)
      #        run: cd /home/runner/work/_actions/gaelgirodon/ci-badges-action && npm i -D @actions/core @actions/github @actions/glob

      #      - name: Upload coverage to gist
      #        uses: gaelgirodon/ci-badges-action@4059134f9f9e113d77dd4f05a47db8b62c09848c
      #        with:
      #          gist-id: d3d51b4f829b93d41e5d809dcf2ef03d
      #          token: ${{ secrets.GH_TOKEN_GISTS }}

      #      - name: Save runtime tests result to gist
      #        uses: exuanbo/actions-deploy-gist@v1
      #        with:
      #          token: ${{ secrets.GH_TOKEN_GISTS }}
      #          gist_id: 67c118e65298627dc0a3745a06387d88
      #          file_path: ./tests/runtimes/results.yaml
